### PR TITLE
Add .gitignore file for Node.js

### PR DESCRIPTION
**Pull request by chengluyu**
It's a common practice to include .gitignore in the project in order to prevent accidentally commit unnecessary files. The file is copied from [github/gitignore](https://github.com/github/gitignore). Hope this helps.

### CODE REVIEW

**Comment by michaschwab** [comment]
Hi chengluyu! Thanks for your pull request! Why are you making this suggestion? Are there any files that you think would be accidentally committed? As far as I know the only potential candidate for this is the dist folder, so this gitignore file seems a bit overkill. What's your thinking? Thanks!

**Comment by chengluyu** [comment]
Hi. I was trying to build this project. After I executed `npm i`, I found that node_modules appeared in the change list of git. This is unusual. Becasue for open source projects, it's a common practice to exclude node_modules from git.

So why did I came up with this PR? In my view, I think this project is excellent. It inspire my current work. Therefore, I think in the future more people will contribute. So creating a gitignore may prevent accidental commit of unnecessary files (e.g. node_modules, error logs from npm or Yarn, temp files, etc). It keeps the project clean.

By the way, I'm also curious about how you prevent committing unnecessary files without the help of the gitignore.

**Comment by michaschwab** [comment]
I just always look at my changelists before committing and by default only commit files that are already tracked. I feel like this large gitignore file is a little overkill but I guess it's fine and I hope it helps accidental commits, so I'm accepting it. Thanks!

**Comment by chengluyu** [comment]
To be honest, only one line of `node_modules` is enough in my scenario. But who knows what will future contributors do? Maybe I'm overconcerned but anyway I'm glad you accepted it.

**Pull request merged**
